FROM php:8.0-fpm-alpine
RUN apk update && apk add gmp-dev
RUN docker-php-ext-install gmp
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN echo "error_reporting=E_ALL" > /usr/local/etc/php/conf.d/boilerplate.ini && \
    echo "log_errors=On"        >> /usr/local/etc/php/conf.d/boilerplate.ini
